-- Diagnóstico: Verificar columnas OCRD en HANA
-- Ejecutar desde Consola SQL del monitor
-- Si una columna falla, el error dice cuál es

SELECT TOP 1
       OCRD.CardCode,
       OCRD.CardName,
       OCRD.CardType,
       OCRD.GroupCode,
       OCRD.Phone1,
       OCRD.Phone2,
       OCRD.Cellular,
       OCRD.Fax,
       OCRD.E_Mail,
       OCRD.IntrntSite,
       OCRD.CntctPrsn,
       OCRD.Notes,
       OCRD.LicTradNum,
       OCRD.VatGroup,
       OCRD.SlpCode,
       OCRD.GroupNum,
       OCRD.Territory,
       OCRD.OwnerCode,
       OCRD.CreateDate,
       OCRD.UpdateDate,
       OCRD.validFor,
       OCRD.frozenFor,
       OCRD.Balance,
       OCRD.Currency,
       OCRD.Address,
       OCRD.Block,
       OCRD.ZipCode,
       OCRD.City,
       OCRD.County,
       OCRD.Country,
       OCRD.State,
       OCRD.Building,
       OCRD.MailAddres,
       OCRD.MailBlock,
       OCRD.MailZipCod,
       OCRD.MailCity,
       OCRD.MailCounty,
       OCRD.MailCountr,
       OCRD.State2,
       OCRD.MailBuildi,
       OCRD.BillToDef,
       OCRD.ShipToDef
  FROM OCRD
 WHERE CardType = 'C'
