-- Migration: Populate production columns in flexo_orders from flexo_calculations
-- The order's raw_data has source_quote_code and source_line_code that match flexo_calculations

UPDATE flexo_orders o
SET
    velocidad_maquina_m_min = fc.velocidad_maquina_m_min,
    tiempo_setup_min = fc.tiempo_setup_min,
    tiempo_montaje_min = fc.tiempo_montaje_min,
    tiempo_limpieza_min = fc.tiempo_limpieza_min,
    costo_hora_maquina = fc.costo_hora_maquina,
    costo_hora_operador = fc.costo_hora_operador,
    subtotal_maquina = fc.subtotal_maquina,
    subtotal_operador = fc.subtotal_operador,
    tiempo_corrida_min = fc.tiempo_corrida_min,
    tiempo_total_impresion_min = fc.tiempo_total_impresion_min,
    tiempo_diseno_horas = fc.tiempo_diseno_horas,
    tiempo_preprensa_horas = fc.tiempo_preprensa_horas,
    tiempo_acabados_min = fc.tiempo_acabados_min,
    tiempo_total_min = fc.tiempo_total_min,
    material_ancho = fc.material_ancho,
    pies_sustrato_neto = fc.pies_sustrato_neto,
    pies_totales_sustrato = fc.pies_totales_sustrato,
    costo_sustrato = fc.costo_sustrato,
    material_msi = fc.material_msi,
    material_m2 = fc.material_m2,
    merma_arranque_pies = fc.merma_arranque_pies,
    merma_tiraje_pies = fc.merma_tiraje_pies,
    merma_tiraje_pct = fc.merma_tiraje_pct,
    costo_merma = fc.costo_merma,
    merma_total_pies = fc.merma_total_pies,
    merma_total_costo = fc.merma_total_costo,
    consumo_tinta_por_color_lb = fc.consumo_tinta_por_color_lb,
    consumo_tinta_total_lb = fc.consumo_tinta_total_lb,
    costo_tinta_por_libra = fc.costo_tinta_por_libra,
    material_tinta_id = fc.material_tinta_id,
    cobertura_tinta_pct = fc.cobertura_tinta_pct,
    bcm_anilox = fc.bcm_anilox,
    factor_transferencia = fc.factor_transferencia,
    densidad_tinta = fc.densidad_tinta,
    costo_libra_cmyk = fc.costo_libra_cmyk,
    costo_libra_blanco = fc.costo_libra_blanco,
    costo_libra_pantone = fc.costo_libra_pantone,
    subtotal_tinta = fc.subtotal_tinta,
    barniz_material_id = fc.barniz_material_id,
    barniz_bcm = fc.barniz_bcm,
    barniz_cobertura_pct = fc.barniz_cobertura_pct,
    barniz_costo_por_kg = fc.barniz_costo_por_kg,
    barniz_zonificado = fc.barniz_zonificado,
    barniz_consumo_kg = fc.barniz_consumo_kg,
    barniz_consumo_lb = fc.barniz_consumo_lb,
    barniz_tiempo_montaje_min = fc.barniz_tiempo_montaje_min,
    barniz_costo_total = fc.barniz_costo_total,
    barniz_comentario = fc.barniz_comentario,
    laminado_material_id = fc.laminado_material_id,
    laminado_pies_lineales = fc.laminado_pies_lineales,
    laminado_costo_por_pie_lineal = fc.laminado_costo_por_pie_lineal,
    laminado_tiempo_montaje_min = fc.laminado_tiempo_montaje_min,
    laminado_costo_total = fc.laminado_costo_total,
    laminado_comentario = fc.laminado_comentario,
    embosado_tiempo_montaje_min = fc.embosado_tiempo_montaje_min,
    embosado_ancho_cliche = fc.embosado_ancho_cliche,
    embosado_largo_cliche = fc.embosado_largo_cliche,
    embosado_costo_cliche = fc.embosado_costo_cliche,
    embosado_comentario = fc.embosado_comentario,
    troquelado_tiempo_montaje_min = fc.troquelado_tiempo_montaje_min,
    troquelado_merma_ajuste_pies = fc.troquelado_merma_ajuste_pies,
    troquelado_comentario = fc.troquelado_comentario,
    numerado_tipo = fc.numerado_tipo,
    numerado_tiempo_montaje_min = fc.numerado_tiempo_montaje_min,
    numerado_costo_fijo = fc.numerado_costo_fijo,
    numerado_comentario = fc.numerado_comentario,
    numerado_adjunto = fc.numerado_adjunto,
    rebobinado_maquina = fc.rebobinado_maquina,
    rebobinado_velocidad = fc.rebobinado_velocidad,
    rebobinado_tiempo_montaje_min = fc.rebobinado_tiempo_montaje_min,
    rebobinado_costo_hora_maquina = fc.rebobinado_costo_hora_maquina,
    rebobinado_costo_operador = fc.rebobinado_costo_operador,
    rebobinado_merma_ajuste_pies = fc.rebobinado_merma_ajuste_pies,
    rebobinado_merma_operacion_pct = fc.rebobinado_merma_operacion_pct,
    rebobinado_tiempo_total_min = fc.rebobinado_tiempo_total_min,
    rebobinado_costo_total = fc.rebobinado_costo_total,
    rebobinado_comentario = fc.rebobinado_comentario,
    empaque_cantidad_rollos = fc.empaque_cantidad_rollos,
    empaque_rendimiento_por_hora = fc.empaque_rendimiento_por_hora,
    empaque_operarios = fc.empaque_operarios,
    empaque_costo_por_operador = fc.empaque_costo_por_operador,
    empaque_costo_externo = fc.empaque_costo_externo,
    empaque_horas = fc.empaque_horas,
    empaque_costo_total = fc.empaque_costo_total,
    empaque_comentario = fc.empaque_comentario
FROM flexo_calculations fc
WHERE fc.quote_code = o.raw_data->>'source_quote_code'
  AND fc.line_code = o.raw_data->>'source_line_code'
  AND (fc.velocidad_maquina_m_min IS NOT NULL
    OR fc.costo_sustrato IS NOT NULL
    OR fc.consumo_tinta_por_color_lb IS NOT NULL
    OR fc.barniz_consumo_lb IS NOT NULL);
