CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS app_config (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    config_key TEXT NOT NULL UNIQUE,
    config_value JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS import_audit (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_name TEXT NOT NULL,
    source_path TEXT NOT NULL,
    records_imported INTEGER NOT NULL DEFAULT 0,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes TEXT
);

CREATE TABLE IF NOT EXISTS business_partners (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    partner_code TEXT UNIQUE,
    prospect_code TEXT,
    partner_name TEXT,
    salesperson_name TEXT,
    tax_id TEXT,
    email TEXT,
    email_facturacion TEXT,
    currency_code TEXT,
    payment_terms TEXT,
    sector TEXT,
    sub_sector TEXT,
    is_tax_exempt BOOLEAN,
    allowed_percentage NUMERIC(12,4),
    client_type TEXT,
    creation_date DATE,
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS business_partner_contacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    partner_code TEXT,
    contact_name TEXT,
    first_name TEXT,
    last_name TEXT,
    email TEXT,
    phone TEXT,
    mobile TEXT,
    fax TEXT,
    position TEXT,
    is_legal_representative BOOLEAN,
    country TEXT,
    state_province TEXT,
    county TEXT,
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS business_partner_addresses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    partner_code TEXT,
    address_name TEXT,
    address_type TEXT,
    country TEXT,
    state_province TEXT,
    county TEXT,
    district TEXT,
    address_line TEXT,
    zip_code TEXT,
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS flexo_machines (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    machine_key TEXT UNIQUE,
    machine_name TEXT,
    brand TEXT,
    model TEXT,
    process TEXT,
    subprocess TEXT,
    category TEXT,
    work_unit TEXT,
    setup_base_minutes NUMERIC(12,4),
    setup_per_station_minutes NUMERIC(12,4),
    setup_extra_minutes NUMERIC(12,4),
    production_speed NUMERIC(12,4),
    hourly_machine_cost NUMERIC(12,4),
    hourly_operator_cost NUMERIC(12,4),
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS flexo_materials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    material_code TEXT UNIQUE,
    material_name TEXT,
    display_name TEXT,
    presentation_type TEXT,
    provider TEXT,
    width_inches NUMERIC(12,4),
    length_value NUMERIC(12,4),
    cost_per_kg_usd NUMERIC(12,4),
    cost_per_linear_meter_usd NUMERIC(12,4),
    cost_per_unit_usd NUMERIC(12,4),
    active BOOLEAN,
    digital_enabled BOOLEAN,
    conventional_enabled BOOLEAN,
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS flexo_dies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    die_code TEXT UNIQUE,
    description TEXT,
    category TEXT,
    dimensions TEXT,
    teeth NUMERIC(12,4),
    rows_count NUMERIC(12,4),
    repetitions NUMERIC(12,4),
    material_width NUMERIC(12,4),
    status TEXT,
    use_digital BOOLEAN,
    use_conventional BOOLEAN,
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS flexo_products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_code TEXT UNIQUE,
    line_code TEXT,
    quote_code TEXT,
    client_code TEXT,
    client_name TEXT,
    product_name TEXT,
    product_type TEXT,
    department TEXT,
    material_name TEXT,
    quoted_machine TEXT,
    die_code TEXT,
    quantity_products NUMERIC(14,4),
    quantity_types NUMERIC(14,4),
    tint_count NUMERIC(14,4),
    width_inches NUMERIC(12,4),
    length_inches NUMERIC(12,4),
    price_unit NUMERIC(14,4),
    total_price NUMERIC(14,4),
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS flexo_cost_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_name TEXT NOT NULL DEFAULT 'default',
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quotes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    quote_code TEXT UNIQUE,
    customer_code TEXT,
    customer_name TEXT,
    contact_name TEXT,
    email TEXT,
    salesperson_name TEXT,
    phone TEXT,
    status TEXT,
    created_on DATE,
    due_on DATE,
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quote_lines (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    quote_code TEXT REFERENCES quotes(quote_code) ON DELETE CASCADE,
    line_code TEXT UNIQUE,
    department TEXT,
    job_name TEXT,
    material_name TEXT,
    status TEXT,
    subtotal_1 NUMERIC(14,4),
    subtotal_2 NUMERIC(14,4),
    subtotal_3 NUMERIC(14,4),
    subtotal_4 NUMERIC(14,4),
    hidden_flag BOOLEAN,
    optional_flag BOOLEAN,
    proof_flag BOOLEAN,
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS flexo_calculations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    calculation_code TEXT UNIQUE,
    quote_code TEXT,
    line_code TEXT,
    product_code TEXT,
    customer_code TEXT,
    process_type TEXT,
    machine_name TEXT,
    die_code TEXT,
    material_code TEXT,
    quantity NUMERIC(14,4),
    subtotal_cost NUMERIC(14,4),
    total_cost NUMERIC(14,4),
    unit_price NUMERIC(14,6),
    customer_name TEXT,
    salesperson_name TEXT,
    job_name TEXT,
    department TEXT DEFAULT 'Flexografia',
    line_status TEXT,
    width_inches NUMERIC(12,4),
    length_inches NUMERIC(12,4),
    labels_per_roll NUMERIC(14,4),
    quantity_types NUMERIC(14,4),
    quantity_changes NUMERIC(14,4),
    core_width NUMERIC(12,4),
    core_diameter TEXT,
    cmyk_enabled BOOLEAN DEFAULT false,
    application_type TEXT,
    surface_type TEXT,
    output_type TEXT,
    industrial_subtotal NUMERIC(14,4),
    overhead_cost NUMERIC(14,4),
    margin_amount NUMERIC(14,4),
    prepress_cost NUMERIC(14,4),
    packaging_cost NUMERIC(14,4),
    design_cost NUMERIC(14,4),
    additional_cost NUMERIC(14,4),
    discount_amount NUMERIC(14,4),
    tax_percent NUMERIC(8,4),
    tax_amount NUMERIC(14,4),
    consumo_tinta_por_color_lb NUMERIC(14,6),
    consumo_tinta_total_lb NUMERIC(14,6),
    costo_tinta_por_libra NUMERIC(14,6),
    material_tinta_id TEXT,
    cobertura_tinta_pct NUMERIC(8,4),
    bcm_anilox NUMERIC(12,4),
    factor_transferencia NUMERIC(8,6),
    densidad_tinta NUMERIC(8,4),
    costo_libra_cmyk NUMERIC(14,6),
    costo_libra_blanco NUMERIC(14,6),
    costo_libra_pantone NUMERIC(14,6),
    subtotal_tinta NUMERIC(14,6),
    merma_arranque_pies NUMERIC(14,4),
    merma_tiraje_pies NUMERIC(14,4),
    merma_tiraje_pct NUMERIC(8,4),
    costo_merma NUMERIC(14,6),
    costo_sustrato NUMERIC(14,6),
    pies_totales_sustrato NUMERIC(14,4),
    pies_sustrato_neto NUMERIC(14,4),
    velocidad_maquina_m_min NUMERIC(12,4),
    tiempo_setup_min NUMERIC(12,4),
    tiempo_montaje_min NUMERIC(12,4),
    tiempo_limpieza_min NUMERIC(12,4),
    costo_hora_maquina NUMERIC(14,6),
    costo_hora_operador NUMERIC(14,6),
    subtotal_maquina NUMERIC(14,6),
    subtotal_operador NUMERIC(14,6),
    tiempo_corrida_min NUMERIC(12,4),
    tiempo_total_impresion_min NUMERIC(12,4),
    barniz_material_id TEXT,
    barniz_bcm NUMERIC(12,4),
    barniz_cobertura_pct NUMERIC(8,4),
    barniz_costo_por_kg NUMERIC(14,6),
    barniz_zonificado BOOLEAN DEFAULT false,
    barniz_comentario TEXT,
    barniz_costo_total NUMERIC(14,6),
    barniz_consumo_kg NUMERIC(14,6),
    barniz_consumo_lb NUMERIC(14,6),
    barniz_tiempo_montaje_min NUMERIC(12,4),
    laminado_material_id TEXT,
    laminado_costo_por_pie_lineal NUMERIC(14,6),
    laminado_tiempo_montaje_min NUMERIC(12,4),
    laminado_comentario TEXT,
    laminado_costo_total NUMERIC(14,6),
    embosado_tiempo_montaje_min NUMERIC(12,4),
    embosado_ancho_cliche NUMERIC(12,4),
    embosado_largo_cliche NUMERIC(12,4),
    embosado_costo_cliche NUMERIC(14,6),
    embosado_comentario TEXT,
    troquelado_tiempo_montaje_min NUMERIC(12,4),
    troquelado_merma_ajuste_pies NUMERIC(14,4),
    troquelado_comentario TEXT,
    numerado_tipo TEXT,
    numerado_tiempo_montaje_min NUMERIC(12,4),
    numerado_costo_fijo NUMERIC(14,6),
    numerado_comentario TEXT,
    numerado_adjunto TEXT,
    rebobinado_maquina TEXT,
    rebobinado_tiempo_montaje_min NUMERIC(12,4),
    rebobinado_costo_hora_maquina NUMERIC(14,6),
    rebobinado_costo_operador NUMERIC(14,6),
    rebobinado_velocidad NUMERIC(12,4),
    rebobinado_merma_ajuste_pies NUMERIC(14,4),
    rebobinado_merma_operacion_pct NUMERIC(8,4),
    rebobinado_comentario TEXT,
    rebobinado_tiempo_total_min NUMERIC(12,4),
    rebobinado_costo_total NUMERIC(14,6),
    empaque_cantidad_rollos NUMERIC(14,4),
    empaque_rendimiento_por_hora NUMERIC(14,4),
    empaque_operarios NUMERIC(8,4),
    empaque_costo_por_operador NUMERIC(14,6),
    empaque_costo_externo NUMERIC(14,6),
    empaque_comentario TEXT,
    empaque_adjunto TEXT,
    empaque_horas NUMERIC(12,4),
    empaque_costo_total NUMERIC(14,6),
    merma_total_pies NUMERIC(14,4),
    merma_total_costo NUMERIC(14,6),
    subtotal_financiero NUMERIC(14,6),
    subtotal_rendimiento NUMERIC(14,6),
    precio_millar NUMERIC(14,6),
    total_colones NUMERIC(14,6),
    tipo_cambio_venta NUMERIC(14,6),
    tipo_cambio_compra NUMERIC(14,6),
    costo_minimo NUMERIC(14,6),
    porcentaje_imprevistos NUMERIC(8,4),
    porcentaje_financiero NUMERIC(8,4),
    porcentaje_iva NUMERIC(8,4),
    porcentaje_adicional NUMERIC(8,4),
    tiempo_diseno_horas NUMERIC(12,4),
    tiempo_preprensa_horas NUMERIC(12,4),
    tiempo_acabados_min NUMERIC(12,4),
    tiempo_total_min NUMERIC(12,4),
    material_m2 NUMERIC(14,4),
    material_msi NUMERIC(14,4),
    material_pies_macula NUMERIC(14,4),
    material_ancho NUMERIC(12,4),
    cantidad_tintas NUMERIC(8,4),
    cantidad_pantones NUMERIC(8,4),
    tinta_blanca BOOLEAN DEFAULT false,
    doble_blanca BOOLEAN DEFAULT false,
    analisis_solicitud TEXT,
    analisis_finalizar TEXT,
    analisis_crear_orden TEXT,
    resumen_cotizacion TEXT,
    info_impresion TEXT,
    observaciones TEXT,
    estado_creacion TEXT,
    condicion_pago TEXT,
    tiempo_entrega TEXT,
    moneda TEXT,
    metodo_envio TEXT,
    tipo_orden TEXT,
    laminado_pies_lineales NUMERIC(14,4),
    ui_state JSONB,
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS flexo_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_code TEXT UNIQUE,
    quote_code TEXT,
    line_code TEXT,
    product_code TEXT,
    machine_name TEXT,
    material_code TEXT,
    die_code TEXT,
    ordered_quantity NUMERIC(14,4),
    delivered_on DATE,
    customer_name TEXT,
    salesperson_name TEXT,
    job_name TEXT,
    process_type TEXT,
    line_status TEXT,
    subtotal_cost NUMERIC(14,4),
    total_cost NUMERIC(14,4),
    unit_price NUMERIC(14,6),
    width_inches NUMERIC(12,4),
    length_inches NUMERIC(12,4),
    labels_per_roll NUMERIC(14,4),
    quantity_types NUMERIC(14,4),
    quantity_changes NUMERIC(14,4),
    core_width NUMERIC(12,4),
    core_diameter TEXT,
    cmyk_enabled BOOLEAN DEFAULT false,
    application_type TEXT,
    output_type TEXT,
    die_teeth NUMERIC(12,4),
    die_rows NUMERIC(12,4),
    die_repeats NUMERIC(12,4),
    material_feet NUMERIC(14,4),
    material_msi NUMERIC(14,4),
    material_m2 NUMERIC(14,4),
    consumo_tinta_por_color_lb NUMERIC(14,6),
    consumo_tinta_total_lb NUMERIC(14,6),
    costo_tinta_por_libra NUMERIC(14,6),
    material_tinta_id TEXT,
    cobertura_tinta_pct NUMERIC(8,4),
    bcm_anilox NUMERIC(12,4),
    factor_transferencia NUMERIC(8,6),
    densidad_tinta NUMERIC(8,4),
    costo_libra_cmyk NUMERIC(14,6),
    costo_libra_blanco NUMERIC(14,6),
    costo_libra_pantone NUMERIC(14,6),
    subtotal_tinta NUMERIC(14,6),
    merma_arranque_pies NUMERIC(14,4),
    merma_tiraje_pies NUMERIC(14,4),
    merma_tiraje_pct NUMERIC(8,4),
    costo_merma NUMERIC(14,6),
    costo_sustrato NUMERIC(14,6),
    pies_totales_sustrato NUMERIC(14,4),
    pies_sustrato_neto NUMERIC(14,4),
    velocidad_maquina_m_min NUMERIC(12,4),
    tiempo_setup_min NUMERIC(12,4),
    tiempo_montaje_min NUMERIC(12,4),
    tiempo_limpieza_min NUMERIC(12,4),
    costo_hora_maquina NUMERIC(14,6),
    costo_hora_operador NUMERIC(14,6),
    subtotal_maquina NUMERIC(14,6),
    subtotal_operador NUMERIC(14,6),
    tiempo_corrida_min NUMERIC(12,4),
    tiempo_total_impresion_min NUMERIC(12,4),
    barniz_material_id TEXT,
    barniz_bcm NUMERIC(12,4),
    barniz_cobertura_pct NUMERIC(8,4),
    barniz_costo_por_kg NUMERIC(14,6),
    barniz_zonificado BOOLEAN DEFAULT false,
    barniz_comentario TEXT,
    barniz_costo_total NUMERIC(14,6),
    barniz_consumo_kg NUMERIC(14,6),
    barniz_consumo_lb NUMERIC(14,6),
    barniz_tiempo_montaje_min NUMERIC(12,4),
    laminado_material_id TEXT,
    laminado_costo_por_pie_lineal NUMERIC(14,6),
    laminado_tiempo_montaje_min NUMERIC(12,4),
    laminado_comentario TEXT,
    laminado_costo_total NUMERIC(14,6),
    embosado_tiempo_montaje_min NUMERIC(12,4),
    embosado_ancho_cliche NUMERIC(12,4),
    embosado_largo_cliche NUMERIC(12,4),
    embosado_costo_cliche NUMERIC(14,6),
    embosado_comentario TEXT,
    troquelado_tiempo_montaje_min NUMERIC(12,4),
    troquelado_merma_ajuste_pies NUMERIC(14,4),
    troquelado_comentario TEXT,
    numerado_tipo TEXT,
    numerado_tiempo_montaje_min NUMERIC(12,4),
    numerado_costo_fijo NUMERIC(14,6),
    numerado_comentario TEXT,
    numerado_adjunto TEXT,
    rebobinado_maquina TEXT,
    rebobinado_tiempo_montaje_min NUMERIC(12,4),
    rebobinado_costo_hora_maquina NUMERIC(14,6),
    rebobinado_costo_operador NUMERIC(14,6),
    rebobinado_velocidad NUMERIC(12,4),
    rebobinado_merma_ajuste_pies NUMERIC(14,4),
    rebobinado_merma_operacion_pct NUMERIC(8,4),
    rebobinado_comentario TEXT,
    rebobinado_tiempo_total_min NUMERIC(12,4),
    rebobinado_costo_total NUMERIC(14,6),
    empaque_cantidad_rollos NUMERIC(14,4),
    empaque_rendimiento_por_hora NUMERIC(14,4),
    empaque_operarios NUMERIC(8,4),
    empaque_costo_por_operador NUMERIC(14,6),
    empaque_costo_externo NUMERIC(14,6),
    empaque_comentario TEXT,
    empaque_adjunto TEXT,
    empaque_horas NUMERIC(12,4),
    empaque_costo_total NUMERIC(14,6),
    merma_total_pies NUMERIC(14,4),
    merma_total_costo NUMERIC(14,6),
    subtotal_financiero NUMERIC(14,6),
    subtotal_rendimiento NUMERIC(14,6),
    precio_millar NUMERIC(14,6),
    total_colones NUMERIC(14,6),
    tipo_cambio_venta NUMERIC(14,6),
    tipo_cambio_compra NUMERIC(14,6),
    costo_minimo NUMERIC(14,6),
    porcentaje_imprevistos NUMERIC(8,4),
    porcentaje_financiero NUMERIC(8,4),
    porcentaje_iva NUMERIC(8,4),
    porcentaje_adicional NUMERIC(8,4),
    tiempo_diseno_horas NUMERIC(12,4),
    tiempo_preprensa_horas NUMERIC(12,4),
    tiempo_acabados_min NUMERIC(12,4),
    tiempo_total_min NUMERIC(12,4),
    material_pies_macula NUMERIC(14,4),
    material_ancho NUMERIC(12,4),
    cantidad_tintas NUMERIC(8,4),
    cantidad_pantones NUMERIC(8,4),
    tinta_blanca BOOLEAN DEFAULT false,
    doble_blanca BOOLEAN DEFAULT false,
    analisis_solicitud TEXT,
    analisis_finalizar TEXT,
    analisis_crear_orden TEXT,
    resumen_cotizacion TEXT,
    info_impresion TEXT,
    observaciones TEXT,
    estado_creacion TEXT,
    condicion_pago TEXT,
    tiempo_entrega TEXT,
    moneda TEXT,
    metodo_envio TEXT,
    tipo_orden TEXT,
    laminado_pies_lineales NUMERIC(14,4),
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_business_partners_name ON business_partners(partner_name);
CREATE INDEX IF NOT EXISTS idx_quotes_customer_code ON quotes(customer_code);
CREATE INDEX IF NOT EXISTS idx_quote_lines_quote_code ON quote_lines(quote_code);
CREATE INDEX IF NOT EXISTS idx_flexo_calculations_quote_code ON flexo_calculations(quote_code);
CREATE INDEX IF NOT EXISTS idx_flexo_orders_quote_code ON flexo_orders(quote_code);
CREATE INDEX IF NOT EXISTS idx_flexo_orders_created_at ON flexo_orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_flexo_orders_line_code ON flexo_orders(line_code);
CREATE INDEX IF NOT EXISTS idx_flexo_orders_quote_line ON flexo_orders(quote_code, line_code);
CREATE INDEX IF NOT EXISTS idx_flexo_calculations_quote_line_created ON flexo_calculations(quote_code, line_code, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_flexo_products_quote_line ON flexo_products(quote_code, line_code);
CREATE INDEX IF NOT EXISTS idx_notification_messages_recipient_read ON notification_center_messages(recipient_user_id, read_at);
CREATE INDEX IF NOT EXISTS idx_notification_participants_user ON notification_center_participants(user_id);